<div class="preview-block">

<?php if ($this->heading): ?>
<h2><?php echo $this->heading; ?></h2>
<?php endif; ?>
<link type="text/css" rel="stylesheet" href="/themes/monaco/lightslider/dist/css/lightslider.css" />                  
<script src="/themes/monaco/lightslider/dist/js/lightslider.js"></script>

<?php
$headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
$bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');

if ($this->heading == 'Fascicules') { //
  
/*
echo $this->universalViewer($this->items, array(
        'class' => 'my-class',
        'style' => 'width: 80%; height: 800px;',
//         'config' => 'https://example.com/my/specific/config.json',
    ));
*/

?>
<ul id="lightSlider" style="margin-left:100px;width=50%;">
<?php


foreach ($this->items as $item):
    $heading = $item->value($headingTerm, ['default' => $this->translate('[Untitled]')]);
    $body = $item->value($bodyTerm);
?>
    <li class="item resource">
        <?php echo $this->thumbnail($item, 'large', ['title' => $heading]); ?>
        <h4><?php echo $item->link($heading); ?></h4>
        <?php if ($body): ?>
        <div class="description"><?php echo $body; ?></div>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
</ul>
    <script type="text/javascript">
      $(document).ready(function() {
        $("#lightSlider").lightSlider({
        item: 1,
        autoWidth: false,
        slideMove: 1, // slidemove will be 1 if loop is true
        slideMargin: 10,
        speed: 400, //ms'
        auto: true,
        loop: true,
        slideEndAnimation: true,
        pause: 5000,}); 
      });
    </script>
    
<?php 
  } else {
    ?>

  
<ul class="resource-list preview">
<?php


foreach ($this->items as $item):
    $heading = $item->value($headingTerm, ['default' => $this->translate('[Untitled]')]);
    $body = $item->value($bodyTerm);
?>
    <li class="item resource">
        <?php echo $this->thumbnail($item, 'medium', ['title' => $heading]); ?>
        <h4><?php echo $item->link($heading); ?></h4>
        <?php if ($body): ?>
        <div class="description"><?php echo $body; ?></div>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
</ul>
<?php
    }
?>
<?php
$linkText = $this->linkText == '' ? $this->translate('Browse all') : $this->linkText;
echo $this->hyperlink($linkText, $this->url(
    'site/resource', ['controller' => 'item', 'action' => 'browse'], ['query' => $this->query], true
));
?>

</div>
