<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Crimson+Text:400,400italic,700,700italic');
$this->headScript()->prependFile($this->assetUrl('js/centerrow.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->partial('common/user-bar', ['site' => $site]);
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <?php echo $userBar; ?>
        <div id="wrap">
            <header>
                <?php if ($this->themeSetting('logo')): ?>
                <a href="<?php echo $site->url(); ?>"><img style="height:80px;" src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" title="Logo"></a>       
                <?php else: ?>
                <a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
                <?php endif; ?>
                <div id="title-site">
                <a href="<?php echo $site->url(); ?>" class="site-title"><span id='title-text'>Campagnes scientifiques d'Albert 1er de Monaco</span></a>                   
            <h3 style="width:100%;text-align:center;">Résultats des campagnes scientifiques accomplies sur son yacht par Albert Ier, Prince Souverain de Monaco</h3>                

              <div id="search">
                <form method="GET" action="<?php echo $site->url(); ?>/rech">
                  <div class="inputs">
                      <input id="searchtext" size="40" name="q" placeholder="Recherche de contenus" value="" type="text" />
                      <button id='recherche-submit' type="submit">&nbsp;</button>
                  </div>
                </form>    
              </div>
             </div>
                                 
            </header>

            <div id="content" role="main">
                <nav>
                <?php
                echo $site->publicNav()->menu()->renderMenu(null, [
                    'ulClass' => 'nav nav-tabs',
                    'maxDepth' => $this->themeSetting('nav_depth') - 1
                ]);
                ?>
                </nav>       
                <?php  // Zend\Debug\Debug::dump($this->params()); 
                  $url = $this->serverUrl(true);
                  if (strpos($url, 'bienvenue')) : ?>
                    <div id="slideshow" style="height:426px;width:643px;margin:0 auto;clear:both;">
                      <img src="/themes/monaco/asset/img/calamar-front.jpeg" />
                    </div>                    
                  <?php endif; ?>

                <?php echo $this->content; ?>
            </div>

            <footer>
                <?php if ($footerContent = $this->themeSetting('footer')): ?>
                <?php echo $footerContent; ?>
                <?php else: ?>
                    <?php  //echo $this->translate('Powered by Omeka S'); ?>
                    <div id="logos-footer">
                    <a href="http://www.institut-ocean.org"><img src="/themes/monaco/asset/img/logo-fondation.png"></a>
                    <a href="https://www.univ-psl.fr"><img src="/themes/monaco/asset/img/logo-psl.png"></a>
                    <a href="http://www.univ-perp.fr"><img src="/themes/monaco/asset/img/perpignan.png"></a>                    
                    <a href="http://www.criobe.pf"><img src="/themes/monaco/asset/img/criobe.png"></a>
                    <a href="http://www.cnrs.fr"><img src="/themes/monaco/asset/img/cnrs.png"></a>
                    <a href="http://www.institut-ocean.org"><img src="/themes/monaco/asset/img/investirlavenir.png"></a>                    
                    </div>
                <?php endif; ?>
            </footer>
        </div>
    </body>
</html>
